### ISSUE TITLE
Nordvpn-Proxy - Add authentication with Roundrobin

### ISSUE THREAD

**Issue by uBadRequest** [ggeorgovassilis/linuxscripts#12]
I've been trying to figure out how to properly do this, but how would you grab all of nord's servers that use socks proxy, and roundrobin between all of them? Also, including the authentication in the HAproxy configuration? Is it like reqadd Proxy-Authentication:?

**Comment by ggeorgovassilis** [comment]
Hi BR,
I know from 1st hand experience that nordvpn doesn't allow switching servers more often than once every 15 minutes. Balancing requests across servers will get your subscription suspended.
Having said that, if you still want to do it: check the find proxy script and modify it to return all servers instead of just the first. Then modify the rest of the scripts to inject those servers into the template.

Sent from mobile, please excuse typos and terseness

________________________________

**Comment by ggeorgovassilis** [comment]
Regarding proxy balancing: I know from 1st hand experience that nordvpn doesn't allow switching servers more often than once every 15 minutes. Balancing requests across servers will get your subscription suspended.
Having said that, if you still want to do it: edit the find [proxy script](https://github.com/ggeorgovassilis/linuxscripts/blob/master/nordvpn-proxy/find-proxy.sh)  and modify it to return all servers instead of just the first. Then modify the rest of the scripts to inject those servers into the template.

Regarding authentication: maybe you can edit the TCP stream towards the proxy and add the authentication - but I wouldn't know how to do this.
[edited for clarity]

**Comment by ggeorgovassilis** [comment]
You might be able to add authentication with an ncat hack [1]. Set up ncat in listening mode so that it forwards connections via a socks5 proxy with authentication.

[1] https://nmap.org/ncat/guide/ncat-proxy.html
