### ISSUE TITLE
NC program error on hasbian image raspberry

### ISSUE THREAD

**Issue by Hitech2207** [ggeorgovassilis/linuxscripts#7]
Hi,

I installed openhab on raspberry using hasbian and when i launch the script using this command:

sudo ./hs100.sh 192.168.0.200 9999 on

i am getting this message:

"The nc programme for sending data over the network isn't in the path, communication with the plug will fail

The same script with same command launched on my mac works without any issue..

What does the message mean?

Thank you

**Comment by ggeorgovassilis** [comment]
I assume you meant "raspbian". The "nc" (or netcat) programme can open network connections and send data over them which the hs100 script uses to communicate with the plug. It seems that nc is either not installed on your respberry or not in the "PATH" variable. I couldn't find instructions about how to install nc on raspbian, presumably because its installed there by default.

Try to type "nc" or "netcat" or "which nc" or "which netcat" on the raspberry command prompt to find out whether its installed already.
"apt-get install netcat" should, normally, install it. 

Btw you don't need "sudo".

**Comment by Hitech2207** [comment]
Hi,

No Hassbian exist it is an Homeassistant image for Raspberry Pi.

But in my case i wanted to talk open the preconfigured image of Openhab which is called OpenHabian.

And it is true that a lot of packages are not installed like NC and other.

I think i will be switching again back to Jessie and install manually Openhab because i don't like Openhabian, too much issues..

Btw installing Netcat did the job it works like a charm using the command through terminal.

Now to make it work with Openhab 2 with Exec binding i need to find the correct command to make it work.

I find online the commando to make it work with the old version of openhanded 1 and the old addon Exec binding but the commando's changed between version...

So still trying to figure it out.

But thank you for the quick reply and keep up the good job :)
